# Generated by Django 5.1.5 on 2025-01-29 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_escrito', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buzon.categoria')),
            ],
        ),
    ]
